package uk.ac.bangor.gcode.newgui;

public class GcodeJFrame extends javax.swing.JFrame {
    
    private static final long serialVersionUID = 4194304381471993483L;

    private final GcodeModel model = new GcodeModel();
    /**
     * Creates new form GcodeJFrame
     */
    public GcodeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gcodeTranslateJPanel = new javax.swing.JPanel();
        inputJScrollPane = new javax.swing.JScrollPane();
        inputJTextArea = new javax.swing.JTextArea();
        outputJScrollPane = new javax.swing.JScrollPane();
        outputJTextArea = new javax.swing.JTextArea();
        translateJButton = new javax.swing.JButton();
        inputFileJLabel = new javax.swing.JLabel();
        inputFileJTextField = new javax.swing.JTextField();
        inputFileJButton = new javax.swing.JButton();
        saveOutputJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        outputFileJLabel = new javax.swing.JLabel();
        outputFileJTextField = new javax.swing.JTextField();
        selectOutputFileJButton = new javax.swing.JButton();
        initialDelayTimeJLabel = new javax.swing.JLabel();
        initialDelayTimeJSpinner = new javax.swing.JSpinner();
        speedJLabel = new javax.swing.JLabel();
        speedJSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputJTextArea.setEditable(false);
        inputJTextArea.setColumns(20);
        inputJTextArea.setRows(5);
        inputJScrollPane.setViewportView(inputJTextArea);

        outputJTextArea.setColumns(20);
        outputJTextArea.setRows(5);
        outputJScrollPane.setViewportView(outputJTextArea);

        translateJButton.setText("Translate");

        inputFileJLabel.setText("Input File:");

        inputFileJButton.setText("Select File");

        saveOutputJButton.setText("Save Output");

        jLabel2.setText("jLabel2");

        outputFileJLabel.setText("Output File:");

        selectOutputFileJButton.setText("Select File");

        initialDelayTimeJLabel.setText("Initial Delay Time:");

        speedJLabel.setText("Spped:");

        javax.swing.GroupLayout gcodeTranslateJPanelLayout = new javax.swing.GroupLayout(gcodeTranslateJPanel);
        gcodeTranslateJPanel.setLayout(gcodeTranslateJPanelLayout);
        gcodeTranslateJPanelLayout.setHorizontalGroup(
            gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gcodeTranslateJPanelLayout.createSequentialGroup()
                        .addComponent(inputFileJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputFileJTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFileJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputJScrollPane)
                    .addComponent(outputJScrollPane)
                    .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                        .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                                .addComponent(saveOutputJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE))
                            .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                                .addComponent(outputFileJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputFileJTextField)
                                .addGap(4, 4, 4)))
                        .addComponent(selectOutputFileJButton))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gcodeTranslateJPanelLayout.createSequentialGroup()
                        .addComponent(initialDelayTimeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initialDelayTimeJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(speedJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(translateJButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gcodeTranslateJPanelLayout.setVerticalGroup(
            gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileJLabel)
                    .addComponent(inputFileJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFileJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initialDelayTimeJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedJLabel)
                    .addComponent(speedJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(translateJButton)
                    .addComponent(initialDelayTimeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectOutputFileJButton)
                    .addGroup(gcodeTranslateJPanelLayout.createSequentialGroup()
                        .addGroup(gcodeTranslateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputFileJLabel)
                            .addComponent(outputFileJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveOutputJButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gcodeTranslateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gcodeTranslateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gcodeTranslateJPanel;
    private javax.swing.JLabel initialDelayTimeJLabel;
    private javax.swing.JSpinner initialDelayTimeJSpinner;
    private javax.swing.JButton inputFileJButton;
    private javax.swing.JLabel inputFileJLabel;
    private javax.swing.JTextField inputFileJTextField;
    private javax.swing.JScrollPane inputJScrollPane;
    private javax.swing.JTextArea inputJTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel outputFileJLabel;
    private javax.swing.JTextField outputFileJTextField;
    private javax.swing.JScrollPane outputJScrollPane;
    private javax.swing.JTextArea outputJTextArea;
    private javax.swing.JButton saveOutputJButton;
    private javax.swing.JButton selectOutputFileJButton;
    private javax.swing.JLabel speedJLabel;
    private javax.swing.JSpinner speedJSpinner;
    private javax.swing.JButton translateJButton;
    // End of variables declaration//GEN-END:variables
}
